try:
    print(name)
except Exception as e:
    print(e)